language: python

python:
  - 2.7

virtualenv:
  system_site_packages: true

notifications:
  email: false

before_install:
- sudo apt-get install -qq python-dev libatlas-base-dev gfortran

install:
  - pip install numpy==1.7
  - pip install -r requirements.txt --use-mirrors

script: nosetests
