language: python

python:
  - 3.3

virtualenv:
  system_site_packages: true

notifications:
  email: false

before_install:
- sudo apt-get install -qq python3-numpy python3-scipy

install:
  - pip install -r requirements.txt --use-mirrors

script: nosetests
